"""
test_manifest.py — unit tests for manifest generation.

All pacman and AUR calls are replaced with injectable fns so no real
system tools are required.
"""
import sys
import io
from contextlib import redirect_stdout, redirect_stderr

import pytest

from unittest.mock import patch
from sysforge.manifest import generate_manifest, _classify, _toml_entry, _make_aur_fn


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Fake repo — packages "known" to pacman
REPO_PKGS = {"htop", "neovim", "mold", "pipewire", "wireplumber"}

def mock_pacman(name):
    return name in REPO_PKGS

def mock_aur(name):
    # Stub — returns None (not found) for everything
    return None

def captured_manifest(names, pacman_fn=mock_pacman, aur_fn=mock_aur):
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        result = generate_manifest(names, pacman_fn=pacman_fn, aur_fn=aur_fn)
    return result, out.getvalue(), err.getvalue()


# ---------------------------------------------------------------------------
# _classify
# ---------------------------------------------------------------------------

def test_classify_repo():
    repo, aur, unknown = _classify(["htop", "neovim"], mock_pacman, mock_aur)
    assert repo == ["htop", "neovim"]
    assert aur == []
    assert unknown == []

def test_classify_unknown():
    repo, aur, unknown = _classify(["totally-fake-pkg"], mock_pacman, mock_aur)
    assert unknown == ["totally-fake-pkg"]
    assert repo == []
    assert aur == []

def test_classify_aur():
    # mock_aur_real returns a value for known aur packages
    def real_aur(name):
        return name if name in {"mesa-git", "cosmic-comp-git"} else None

    repo, aur, unknown = _classify(
        ["htop", "mesa-git", "nonexistent"],
        mock_pacman, real_aur,
    )
    assert repo == ["htop"]
    assert aur == ["mesa-git"]
    assert unknown == ["nonexistent"]

def test_classify_mixed():
    repo, aur, unknown = _classify(
        ["htop", "fake-pkg", "neovim"],
        mock_pacman, mock_aur,
    )
    assert repo == ["htop", "neovim"]
    assert unknown == ["fake-pkg"]


# ---------------------------------------------------------------------------
# _toml_entry
# ---------------------------------------------------------------------------

def test_toml_entry_repo():
    entry = _toml_entry("htop", "repo")
    assert '[[package]]' in entry
    assert 'name = "htop"' in entry
    assert 'source = "repo"' in entry

def test_toml_entry_aur():
    entry = _toml_entry("mesa-git", "aur")
    assert 'source = "aur"' in entry


# ---------------------------------------------------------------------------
# generate_manifest
# ---------------------------------------------------------------------------

def test_manifest_repo_packages():
    result, _, _ = captured_manifest(["htop", "neovim"])
    assert 'name = "htop"' in result
    assert 'name = "neovim"' in result
    assert 'source = "repo"' in result

def test_manifest_has_build_section():
    result, _, _ = captured_manifest(["htop"])
    assert "[build]" in result
    assert "pkgbuild_dir" in result

def test_manifest_has_header_comment():
    result, _, _ = captured_manifest(["htop"])
    assert "Generated by sysforge manifest" in result

def test_manifest_unknown_excluded(capsys):
    result, _, err = captured_manifest(["htop", "fake-pkg"])
    assert 'name = "fake-pkg"' not in result
    assert "fake-pkg" in err
    assert "excluded" in err

def test_manifest_unknown_warning_to_stderr():
    _, _, err = captured_manifest(["totally-unknown"])
    assert "not found" in err
    assert "totally-unknown" in err

def test_manifest_aur_packages_logged():
    def aur_finds_it(name):
        return name  # pretend AUR found it

    _, _, err = captured_manifest(
        ["mesa-git"], pacman_fn=lambda n: False, aur_fn=aur_finds_it
    )
    # AUR packages are logged at INFO level (visible in tests at verbosity 2)
    assert "aur" in err.lower()


def test_make_aur_fn_returns_name_if_found():
    with patch("sysforge.manifest.aur_info", return_value={"mesa-git": {"Name": "mesa-git"}}):
        fn = _make_aur_fn(["mesa-git", "nonexistent"])
    assert fn("mesa-git") == "mesa-git"
    assert fn("nonexistent") is None


def test_make_aur_fn_empty_on_network_error():
    with patch("sysforge.manifest.aur_info", return_value={}):
        fn = _make_aur_fn(["mesa-git"])
    assert fn("mesa-git") is None


def test_generate_manifest_uses_real_aur_fn():
    """generate_manifest with aur_fn=None calls aur_info once for all names."""
    aur_results = {"mesa-git": {"Name": "mesa-git"}}
    with patch("sysforge.manifest.aur_info", return_value=aur_results) as mock_aur:
        result, _, _ = captured_manifest(
            ["htop", "mesa-git"], pacman_fn=mock_pacman, aur_fn=None
        )
    # aur_info should have been called once (batch), not per-package
    mock_aur.assert_called_once()
    assert 'name = "mesa-git"' in result
    assert 'source = "aur"' in result

def test_manifest_empty_result_when_all_unknown():
    result, _, _ = captured_manifest(["fake1", "fake2"])
    assert '[[package]]' not in result

def test_manifest_preserves_order():
    result, _, _ = captured_manifest(["neovim", "htop", "mold"])
    pos_neovim = result.index('name = "neovim"')
    pos_htop   = result.index('name = "htop"')
    pos_mold   = result.index('name = "mold"')
    assert pos_neovim < pos_htop < pos_mold

def test_manifest_stdout_note_to_stderr():
    _, _, err = captured_manifest(["htop"])
    assert "stdout" in err.lower()
    assert "saved" in err.lower()

def test_manifest_deduplicates_names():
    result, _, _ = captured_manifest(["htop", "htop", "neovim"])
    assert result.count('name = "htop"') == 1

def test_manifest_all_repo_no_aur_section():
    result, _, _ = captured_manifest(["htop", "neovim"])
    assert "AUR packages" not in result

def test_manifest_repo_section_header():
    result, _, _ = captured_manifest(["htop"])
    assert "Repo packages" in result
