"""
test_manifest.py — unit tests for manifest generation.

All pacman and AUR calls are replaced with injectable fns so no real
system tools are required.
"""
import sys
import io
from contextlib import redirect_stdout, redirect_stderr

import pytest

from unittest.mock import patch
from sysforge.manifest import generate_manifest, _classify, _toml_entry, _make_aur_fn


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

# Fake repo — packages "known" to pacman
REPO_PKGS = {"htop", "neovim", "mold", "pipewire", "wireplumber"}

def mock_pacman(name):
    return name in REPO_PKGS

def mock_aur(name):
    # Stub — returns None (not found) for everything
    return None

def captured_manifest(names, pacman_fn=mock_pacman, aur_fn=mock_aur):
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        result = generate_manifest(names, pacman_fn=pacman_fn, aur_fn=aur_fn)
    return result, out.getvalue(), err.getvalue()


# ---------------------------------------------------------------------------
# _classify
# ---------------------------------------------------------------------------

def test_classify_repo():
    repo, aur, unknown = _classify(["htop", "neovim"], mock_pacman, mock_aur)
    assert repo == ["htop", "neovim"]
    assert aur == []
    assert unknown == []

def test_classify_unknown():
    repo, aur, unknown = _classify(["totally-fake-pkg"], mock_pacman, mock_aur)
    assert unknown == ["totally-fake-pkg"]
    assert repo == []
    assert aur == []

def test_classify_aur():
    # mock_aur_real returns a value for known aur packages
    def real_aur(name):
        return name if name in {"mesa-git", "cosmic-comp-git"} else None

    repo, aur, unknown = _classify(
        ["htop", "mesa-git", "nonexistent"],
        mock_pacman, real_aur,
    )
    assert repo == ["htop"]
    assert aur == ["mesa-git"]
    assert unknown == ["nonexistent"]

def test_classify_mixed():
    repo, aur, unknown = _classify(
        ["htop", "fake-pkg", "neovim"],
        mock_pacman, mock_aur,
    )
    assert repo == ["htop", "neovim"]
    assert unknown == ["fake-pkg"]


# ---------------------------------------------------------------------------
# _toml_entry
# ---------------------------------------------------------------------------

def test_toml_entry_repo():
    entry = _toml_entry("htop", "repo")
    assert '[[package]]' in entry
    assert 'name = "htop"' in entry
    assert 'source = "repo"' in entry

def test_toml_entry_aur():
    entry = _toml_entry("mesa-git", "aur")
    assert 'source = "aur"' in entry


# ---------------------------------------------------------------------------
# generate_manifest
# ---------------------------------------------------------------------------

def test_manifest_repo_packages():
    result, _, _ = captured_manifest(["htop", "neovim"])
    assert 'name = "htop"' in result
    assert 'name = "neovim"' in result
    assert 'source = "repo"' in result

def test_manifest_has_build_section():
    result, _, _ = captured_manifest(["htop"])
    assert "[build]" in result
    assert "pkgbuild_dir" in result

def test_manifest_has_header_comment():
    result, _, _ = captured_manifest(["htop"])
    assert "Generated by sysforge manifest" in result

def test_manifest_unknown_excluded(capsys):
    result, _, err = captured_manifest(["htop", "fake-pkg"])
    assert 'name = "fake-pkg"' not in result
    assert "fake-pkg" in err
    assert "excluded" in err

def test_manifest_unknown_warning_to_stderr():
    _, _, err = captured_manifest(["totally-unknown"])
    assert "not found" in err
    assert "totally-unknown" in err

def test_manifest_aur_packages_logged():
    def aur_finds_it(name):
        return name  # pretend AUR found it

    _, _, err = captured_manifest(
        ["mesa-git"], pacman_fn=lambda n: False, aur_fn=aur_finds_it
    )
    # AUR packages are logged at INFO level (visible in tests at verbosity 2)
    assert "aur" in err.lower()


def test_make_aur_fn_returns_name_if_found():
    with patch("sysforge.manifest.aur_info", return_value={"mesa-git": {"Name": "mesa-git"}}):
        fn = _make_aur_fn(["mesa-git", "nonexistent"])
    assert fn("mesa-git") == "mesa-git"
    assert fn("nonexistent") is None


def test_make_aur_fn_empty_on_network_error():
    with patch("sysforge.manifest.aur_info", return_value={}):
        fn = _make_aur_fn(["mesa-git"])
    assert fn("mesa-git") is None


def test_generate_manifest_uses_real_aur_fn():
    """generate_manifest with aur_fn=None calls aur_info once for all names."""
    aur_results = {"mesa-git": {"Name": "mesa-git"}}
    with patch("sysforge.manifest.aur_info", return_value=aur_results) as mock_aur:
        result, _, _ = captured_manifest(
            ["htop", "mesa-git"], pacman_fn=mock_pacman, aur_fn=None
        )
    # aur_info should have been called once (batch), not per-package
    mock_aur.assert_called_once()
    assert 'name = "mesa-git"' in result
    assert 'source = "aur"' in result

def test_manifest_empty_result_when_all_unknown():
    result, _, _ = captured_manifest(["fake1", "fake2"])
    assert '[[package]]' not in result

def test_manifest_preserves_order():
    result, _, _ = captured_manifest(["neovim", "htop", "mold"])
    pos_neovim = result.index('name = "neovim"')
    pos_htop   = result.index('name = "htop"')
    pos_mold   = result.index('name = "mold"')
    assert pos_neovim < pos_htop < pos_mold

def test_manifest_stdout_note_to_stderr():
    _, _, err = captured_manifest(["htop"])
    assert "stdout" in err.lower()
    assert "saved" in err.lower()

def test_manifest_deduplicates_names():
    result, _, _ = captured_manifest(["htop", "htop", "neovim"])
    assert result.count('name = "htop"') == 1

def test_manifest_all_repo_no_aur_section():
    result, _, _ = captured_manifest(["htop", "neovim"])
    assert "AUR packages" not in result

def test_manifest_repo_section_header():
    result, _, _ = captured_manifest(["htop"])
    assert "Repo packages" in result


# ---------------------------------------------------------------------------
# _toml_entry — profile field
# ---------------------------------------------------------------------------

def test_toml_entry_with_profile():
    entry = _toml_entry("mesa-git", "aur", profile="patched")
    assert 'profile = "patched"' in entry

def test_toml_entry_no_profile_omitted():
    entry = _toml_entry("mesa-git", "aur")
    assert "profile" not in entry

def test_toml_entry_none_profile_omitted():
    entry = _toml_entry("mesa-git", "aur", profile=None)
    assert "profile" not in entry


# ---------------------------------------------------------------------------
# generate_manifest — dirty detection
# ---------------------------------------------------------------------------

AUR_PKGS = {"mesa-git", "linux-custom", "cosmic-comp-git"}

def mock_aur_found(name):
    return name if name in AUR_PKGS else None

def captured_manifest_with_dirty(names, dirty_fn):
    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err):
        result = generate_manifest(
            names,
            pacman_fn=lambda n: False,
            aur_fn=mock_aur_found,
            dirty_fn=dirty_fn,
        )
    return result, out.getvalue(), err.getvalue()


def test_manifest_dirty_package_gets_profile_patched():
    result, _, _ = captured_manifest_with_dirty(
        ["mesa-git", "linux-custom"],
        dirty_fn=lambda name: name == "mesa-git",
    )
    # mesa-git is dirty → should have profile = "patched"
    lines = result.splitlines()
    mesa_idx = next(i for i, l in enumerate(lines) if 'name = "mesa-git"' in l)
    assert any('profile = "patched"' in l for l in lines[mesa_idx:mesa_idx + 5])


def test_manifest_clean_package_has_no_profile():
    result, _, _ = captured_manifest_with_dirty(
        ["mesa-git", "linux-custom"],
        dirty_fn=lambda name: name == "mesa-git",
    )
    lines = result.splitlines()
    linux_idx = next(i for i, l in enumerate(lines) if 'name = "linux-custom"' in l)
    block = lines[linux_idx:linux_idx + 5]
    assert not any("profile" in l for l in block)


def test_manifest_no_dirty_no_profiles():
    result, _, _ = captured_manifest_with_dirty(
        ["mesa-git", "linux-custom"],
        dirty_fn=lambda name: False,
    )
    assert 'profile = "patched"' not in result


def test_manifest_all_dirty():
    result, _, _ = captured_manifest_with_dirty(
        ["mesa-git", "linux-custom"],
        dirty_fn=lambda name: True,
    )
    assert result.count('profile = "patched"') == 2


def test_manifest_dirty_fn_none_uses_pkgbuild_dir(tmp_path):
    """When dirty_fn is None, _make_dirty_fn is called with pkgbuild_dir."""
    pkg_dir = tmp_path / "mesa-git"
    pkg_dir.mkdir()
    (pkg_dir / "PKGBUILD").touch()

    # Simulate a dirty repo via git subprocess mock
    import subprocess as sp
    def fake_git(cmd, **kwargs):
        cmd_str = " ".join(cmd)
        if "--git-dir" in cmd_str:
            return sp.CompletedProcess(cmd, 0, stdout=".git", stderr="")
        if "status" in cmd_str:
            return sp.CompletedProcess(cmd, 0, stdout=" M PKGBUILD\n", stderr="")
        return sp.CompletedProcess(cmd, 0, stdout="", stderr="")

    out = io.StringIO()
    err = io.StringIO()
    with redirect_stdout(out), redirect_stderr(err), \
         patch("subprocess.run", side_effect=fake_git):
        result = generate_manifest(
            ["mesa-git"],
            pacman_fn=lambda n: False,
            aur_fn=lambda n: n if n == "mesa-git" else None,
            pkgbuild_dir=tmp_path,
        )

    assert 'profile = "patched"' in result
