"""
manifest.py — packages.toml generator

Queries pacman sync DBs to determine package source, then generates a
packages.toml stub to stdout.

Source detection:
  repo  — found in pacman sync DBs (pacman -Si)
  aur   — confirmed via AUR RPC v5 batch query
  unknown — not found anywhere; excluded with a warning

Public API:
    generate_manifest(names, pacman_fn=None, aur_fn=None) -> str
    cmd_manifest(args)
"""
import sysforge.log as _log
import sys
from pathlib import Path
from typing import Callable

from sysforge.primitives.aur import aur_info, git_is_dirty, is_repo_package


# ---------------------------------------------------------------------------
# Source detection
# ---------------------------------------------------------------------------


def _make_aur_fn(names: list[str]) -> Callable[[str], str | None]:
    """
    Build a per-name AUR lookup function via a single batch RPC call.
    Returns a closure: returns name if found in AUR, else None.
    """
    found = aur_info(names)
    return lambda name: name if name in found else None


def _classify(names, pacman_fn, aur_fn):
    """
    Classify each name into repo, aur, or unknown.
    Returns (repo: list, aur: list, unknown: list).
    """
    repo, aur, unknown = [], [], []

    for name in names:
        if pacman_fn(name):
            repo.append(name)
        else:
            aur_result = aur_fn(name)
            if aur_result is not None:
                aur.append(name)
            else:
                unknown.append(name)

    return repo, aur, unknown


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------

def _toml_entry(name, source, profile=None):
    lines = [
        "[[package]]",
        f'name = "{name}"',
        f'source = "{source}"',
    ]
    if profile:
        lines.append(f'profile = "{profile}"')
    return "\n".join(lines)


def _make_dirty_fn(pkgbuild_dir: Path | None) -> Callable[[str], bool]:
    """
    Return a function that checks whether a package's local PKGBUILD dir has
    uncommitted changes. Returns False for all packages when pkgbuild_dir is
    unset or when the directory doesn't exist / isn't a git repo.
    """
    if pkgbuild_dir is None:
        return lambda name: False

    def _check(name: str) -> bool:
        local_dir = pkgbuild_dir / name
        if not local_dir.is_dir():
            return False
        return git_is_dirty(local_dir)

    return _check


def generate_manifest(names, pacman_fn=None, aur_fn=None, dirty_fn=None,
                      pkgbuild_dir: Path | None = None):
    """
    Generate a packages.toml string for the given package names.

    Queries pacman (and the AUR stub) to classify each name.
    Unknown packages are excluded and logged to stderr.
    Duplicates are removed while preserving order.

    Returns the TOML string (ready to write to a file).
    """
    if pacman_fn is None:
        pacman_fn = is_repo_package

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for n in names:
        if n not in seen:
            seen.add(n)
            unique.append(n)

    if aur_fn is None:
        aur_fn = _make_aur_fn(unique)

    if dirty_fn is None:
        dirty_fn = _make_dirty_fn(pkgbuild_dir)

    repo, aur, unknown = _classify(unique, pacman_fn, aur_fn)

    if unknown:
        _log.warn("[MANIFEST]", f"Warning: {len(unknown)} package(s) not found in repos or AUR — excluded from output: {unknown}")

    if aur:
        _log.info("[MANIFEST]", f"{len(aur)} package(s) confirmed on AUR: {aur}")

    dirty = [n for n in aur if dirty_fn(n)]
    if dirty:
        _log.info("[MANIFEST]", f"{len(dirty)} AUR package(s) have local uncommitted changes — setting profile = \"patched\": {dirty}")

    lines = [
        "# Generated by sysforge manifest",
        "# Review before use — optional fields (profile, cache, requires_hardware)",
        "# must be added manually where needed.",
        "",
        "[build]",
        'pkgbuild_dir = "~/builds"  # update to your actual AUR build directory',
        "",
    ]

    if repo:
        lines.append("# ── Repo packages ──────────────────────────────────────────────")
        lines.append("")
        for name in repo:
            lines.append(_toml_entry(name, "repo"))
            lines.append("")

    if aur:
        lines.append("# ── AUR packages ───────────────────────────────────────────────")
        lines.append("")
        for name in aur:
            profile = "patched" if dirty_fn(name) else None
            lines.append(_toml_entry(name, "aur", profile=profile))
            lines.append("")

    _log.info("[MANIFEST]", "Output written to stdout. If you redirected to a file it has been saved.\n[SYSFORGE][INFO][MANIFEST] Example:  sysforge manifest htop neovim > packages.toml")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def cmd_manifest(args):
    """
    Entry point called from cli.py.
    Reads package names from args.packages (list) and/or args.file (path).
    Prints generated TOML to stdout.
    """
    names = []

    if args.packages:
        names.extend(args.packages)

    if args.file:
        try:
            with open(args.file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        names.extend(line.split())
        except FileNotFoundError:
            _log.error("[MANIFEST]", f"File not found: {args.file}")
            sys.exit(1)

    if not names:
        _log.error("[MANIFEST]", "No package names provided. Pass names directly or use --file.")
        sys.exit(1)

    from sysforge.primitives.config import load_config
    config = load_config()
    raw_pkgbuild_dir = config.get("paths", {}).get("pkgbuild_dir") if config else None
    pkgbuild_dir = Path(raw_pkgbuild_dir).expanduser() if raw_pkgbuild_dir else None

    output = generate_manifest(names, pkgbuild_dir=pkgbuild_dir)
    print(output)
