"""
manifest.py — packages.toml generator

Queries pacman sync DBs to determine package source, then generates a
packages.toml stub to stdout.

Source detection:
  repo  — found in pacman sync DBs (pacman -Si)
  aur   — not in repos; AUR RPC lookup (stub: marked aur, logged for manual review)
  unknown — not found anywhere; excluded with a warning

Public API:
    generate_manifest(names, pacman_fn=None, aur_fn=None) -> str
    cmd_manifest(args)
"""
import subprocess
import sysforge.log as _log
import sys
from typing import Callable


# ---------------------------------------------------------------------------
# Source detection
# ---------------------------------------------------------------------------

def _default_pacman_si(name):
    """
    Return True if name exists in pacman sync DBs.
    Uses pacman -Si which queries sync repos without installing anything.
    """
    result = subprocess.run(
        ["pacman", "-Si", name],
        capture_output=True,
    )
    return result.returncode == 0


def _stub_aur_fn(name):
    """
    Stub AUR lookup — always returns None (unknown).
    Replace with real AUR RPC call when ready.
    """
    return None   # None = not found in AUR (stub)


def _classify(names, pacman_fn, aur_fn):
    """
    Classify each name into repo, aur, or unknown.
    Returns (repo: list, aur: list, unknown: list).
    """
    repo, aur, unknown = [], [], []

    for name in names:
        if pacman_fn(name):
            repo.append(name)
        else:
            aur_result = aur_fn(name)
            if aur_result is not None:
                aur.append(name)
            else:
                unknown.append(name)

    return repo, aur, unknown


# ---------------------------------------------------------------------------
# TOML generation
# ---------------------------------------------------------------------------

def _toml_entry(name, source):
    lines = [
        "[[package]]",
        f'name = "{name}"',
        f'source = "{source}"',
    ]
    return "\n".join(lines)


def generate_manifest(names, pacman_fn=None, aur_fn=None):
    """
    Generate a packages.toml string for the given package names.

    Queries pacman (and the AUR stub) to classify each name.
    Unknown packages are excluded and logged to stderr.
    Duplicates are removed while preserving order.

    Returns the TOML string (ready to write to a file).
    """
    if pacman_fn is None:
        pacman_fn = _default_pacman_si
    if aur_fn is None:
        aur_fn = _stub_aur_fn

    # Deduplicate while preserving order
    seen = set()
    unique = []
    for n in names:
        if n not in seen:
            seen.add(n)
            unique.append(n)

    repo, aur, unknown = _classify(unique, pacman_fn, aur_fn)

    if unknown:
        _log.warn("[MANIFEST]", f"Warning: {len(unknown)} package(s) not found in repos or AUR — excluded from output: {unknown}")

    if aur:
        _log.warn("[MANIFEST]", f"Note: {len(aur)} package(s) classified as AUR (AUR lookup is stubbed — verify manually): {aur}")

    lines = [
        "# Generated by sysforge manifest",
        "# Review before use — optional fields (pkgbuild_patch, cache, requires_hardware)",
        "# must be added manually where needed.",
        "",
        "[build]",
        'pkgbuild_dir = "~/builds"  # update to your actual AUR build directory',
        "",
    ]

    if repo:
        lines.append("# ── Repo packages ──────────────────────────────────────────────")
        lines.append("")
        for name in repo:
            lines.append(_toml_entry(name, "repo"))
            lines.append("")

    if aur:
        lines.append("# ── AUR packages ───────────────────────────────────────────────")
        lines.append("")
        for name in aur:
            lines.append(_toml_entry(name, "aur"))
            lines.append("")

    _log.info("[MANIFEST]", "Output written to stdout. If you redirected to a file it has been saved.\n[SYSFORGE][INFO][MANIFEST] Example:  sysforge manifest htop neovim > packages.toml")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def cmd_manifest(args):
    """
    Entry point called from cli.py.
    Reads package names from args.packages (list) and/or args.file (path).
    Prints generated TOML to stdout.
    """
    names = []

    if args.packages:
        names.extend(args.packages)

    if args.file:
        try:
            with open(args.file) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        names.extend(line.split())
        except FileNotFoundError:
            _log.error("[MANIFEST]", f"File not found: {args.file}")
            sys.exit(1)

    if not names:
        _log.error("[MANIFEST]", "No package names provided. Pass names directly or use --file.")
        sys.exit(1)

    output = generate_manifest(names)
    print(output)
