"""
makepkg_wrapper.py — build execution

Responsible for conf file emission, makepkg invocation, retry logic,
and the top-level run() entry point. All config loading, profile resolution,
and PKGBUILD parsing are delegated to their respective modules.

Public API:
    run(pkgbuild_path)
"""
import contextlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from sysforge.primitives.config import (
    load_config,
    load_conflict_groups,
    load_consumes_inference,
    parse_system_makepkg_conf,
)
from sysforge.primitives.pkgbuild_meta import parse_pkgbuild
from sysforge.primitives.pkgbuild_patcher import (
    apply_patch_pkgbuild,
    cleanup_patch_artifacts,
    extract_pkgbuild_profile,
    patch_pkgbuild_groups,
    write_extracted_profile,
)
from sysforge.primitives.dep_analysis import run_dep_analysis
from sysforge.primitives.failure import handle_failure
import sysforge.log as _log
from sysforge.primitives.profile import (
    _CONF_KEY_MAP,
    _SYSFORGE_KEYS,
    match_rules,
    resolve_consumes,
    resolve_groups,
    resolve_profile,
)


# ---------------------------------------------------------------------------
# Conf file emission
# ---------------------------------------------------------------------------

@contextlib.contextmanager
def emit_makepkg_conf(resolved_profile, active_consumes=None,
                      system_conf_path=None):
    """
    Write a complete, self-contained temp makepkg.conf by merging:
      1. All keys from /etc/makepkg.conf (system baseline)
      2. Profile-managed keys from resolved_profile (override)

    Keys in the system conf that sysforge doesn't manage (CARCH, CHOST,
    PKGDEST, PACKAGER, etc.) are written verbatim from the system conf.
    Profile keys overwrite their system counterparts; profile keys absent
    from the system conf are appended at the end.

    "env" type keys and sysforge-internal keys are never written to the conf.
    """
    env_keys = _CONF_KEY_MAP.get("env", set())

    if active_consumes is None:
        allowed_keys = None
    else:
        allowed_keys: set[str] = set()
        for conf_type in active_consumes:
            if conf_type == "env":
                continue
            if conf_type in _CONF_KEY_MAP:
                allowed_keys.update(_CONF_KEY_MAP[conf_type])

    # Profile keys to write: filter out internal, env-pass, and out-of-consumes keys
    profile_overrides = {}
    for key, val in resolved_profile.items():
        if key in _SYSFORGE_KEYS:
            continue
        if key in env_keys:
            continue
        if allowed_keys is not None and key not in allowed_keys:
            continue
        profile_overrides[key] = val

    # Load system conf baseline
    system_assignments = parse_system_makepkg_conf(system_conf_path)

    # Build output lines: system conf keys in their original raw form,
    # profile-overridden keys substituted inline, new profile keys appended.
    conf_lines = ["# Generated by SysForge — merged system conf + profile overrides"]

    for key, raw_val in system_assignments.items():
        if key in env_keys:
            # Env-type keys are injected via subprocess env, never written to conf —
            # even if the system conf has them set.
            continue
        if key in profile_overrides:
            conf_lines.append(f'{key}="{profile_overrides[key]}"')
        else:
            conf_lines.append(f"{key}={raw_val}")

    new_keys = [k for k in profile_overrides if k not in system_assignments]
    if new_keys:
        conf_lines.append("")
        conf_lines.append("# SysForge profile additions (not in system conf)")
        for key in new_keys:
            conf_lines.append(f'{key}="{profile_overrides[key]}"')

    with tempfile.NamedTemporaryFile(
        mode="w",
        prefix="sysforge_makepkg_",
        suffix=".conf",
        delete=False,
    ) as f:
        f.write("\n".join(conf_lines) + "\n")
        tmp_path = f.name

    _log.info("[CONF]", f"Wrote temp makepkg.conf: {tmp_path}")
    try:
        yield tmp_path
    finally:
        os.unlink(tmp_path)
        _log.info("[CONF]", f"Removed temp makepkg.conf: {tmp_path}")


# ---------------------------------------------------------------------------
# Env var resolution and build invocation
# ---------------------------------------------------------------------------

def resolve_env_vars(resolved_profile, active_consumes=None):
    """
    Extract profile keys that travel via subprocess env injection rather than
    the makepkg.conf temp file.

    Two categories are collected:
      1. Keys in the "env" conf type — explicitly designated for env injection
         (e.g. RUSTC_WRAPPER, CCACHE_DIR). Only collected when "env" is in
         active_consumes or active_consumes is None (fallback mode).
      2. Unknown keys — not in any _CONF_KEY_MAP type and not in _SYSFORGE_KEYS.
         These are always collected and logged under [ENV] as a warning, since
         their presence may indicate a typo or a new key that needs classifying.

    Returns dict[str, str] of key -> value pairs to inject on invocation.
    Empty dict if nothing to inject.
    """
    env_type_keys = _CONF_KEY_MAP.get("env", set())

    # All keys that are explicitly classified into a non-env conf type
    all_conf_keys: set[str] = set()
    for conf_type, keys in _CONF_KEY_MAP.items():
        if conf_type != "env":
            all_conf_keys.update(keys)

    collect_env_type = active_consumes is None or "env" in active_consumes

    result: dict[str, str] = {}
    unknown: list[str] = []

    for key, val in resolved_profile.items():
        if key in _SYSFORGE_KEYS:
            continue

        if key in env_type_keys:
            if collect_env_type:
                result[key] = val
                _log.info("[ENV]", f"Injecting (env type): {key}={val!r}")
            continue

        if key not in all_conf_keys:
            # Unknown key — not classified; env pass with warning
            result[key] = val
            unknown.append(key)

    if unknown:
        _log.warn("[ENV]", f"Unclassified profile keys injected via env (consider adding to _CONF_KEY_MAP): {sorted(unknown)}")

    return result


def invoke_makepkg(pkgbuild_path, conf_path, resolved_profile,
                   extra_env=None, extra_flags=None, interactive=False):
    pkgbuild_path = Path(pkgbuild_path).resolve()
    build_dir = pkgbuild_path.parent

    env = os.environ.copy()
    env["MAKEPKG_CONF"] = str(conf_path)

    if extra_env:
        env.update(extra_env)
        _log.info("[ENV]", f"Injecting {len(extra_env)} env var(s): {sorted(extra_env.keys())}")

    flags = list(resolved_profile.get("makepkg_flags", []))
    if interactive:
        flags = [f for f in flags if f != "--noconfirm"]
        _log.info("[BUILD]", "--interactive: stripped --noconfirm from profile flags")
    if extra_flags:
        flags += extra_flags
        _log.info("[BUILD]", f"Appending CLI flags: {extra_flags}")
    cmd = ["makepkg"] + flags

    _log.info("[BUILD]", f"Running {' '.join(cmd)} in {build_dir} with MAKEPKG_CONF={conf_path}")

    result = subprocess.run(cmd, cwd=build_dir, env=env)

    if result.returncode != 0:
        raise subprocess.CalledProcessError(result.returncode, "makepkg")


def _invoke_with_retry(pkgbuild_path, conf_path, resolved_profile,
                       extra_env=None, extra_flags=None, interactive=False):
    """
    Invoke makepkg, retrying after manual correction if not in batch mode.
    """
    if resolved_profile.get("batch", False):
        try:
            invoke_makepkg(pkgbuild_path, conf_path, resolved_profile,
                           extra_env, extra_flags, interactive)
        except subprocess.CalledProcessError as e:
            _log.error("[BUILD]", f"Build failed in batch mode, aborting: {e}")
            raise RuntimeError(f"[build_failed] {e}")
    else:
        while True:
            try:
                invoke_makepkg(pkgbuild_path, conf_path, resolved_profile,
                               extra_env, extra_flags, interactive)
                break
            except subprocess.CalledProcessError as e:
                _log.error("[BUILD]", f"Build failed: {e}")
                _log.info("[BUILD]", f"PKGBUILD location: {pkgbuild_path}")
                response = (
                    input(
                        "[BUILD] Manually correct the PKGBUILD and press Enter to retry, "
                        "or type 'abort' to stop: "
                    )
                    .strip()
                    .lower()
                )
                if response == "abort":
                    raise RuntimeError(
                        "[build_failed] Aborted by user after build failure"
                    )
                _log.info("[BUILD]", "Retrying build...")


def _run_build(pkgbuild_path, resolved_profile, config, groups,
               active_consumes=None, extracted_profile=None, pkgmeta=None,
               extra_flags=None, interactive=False):
    """
    Emit makepkg.conf and invoke makepkg, handling build failures.

    If extracted_profile is provided (patch_pkgbuild mode), applies the
    patched PKGBUILD instead of the original. Cleans up patch artifacts on
    success; leaves them in place on failure for diagnosis.
    """
    if extracted_profile is not None:
        # patch_pkgbuild mode: use patched copy with flags stripped
        pkgbuild_path = apply_patch_pkgbuild(
            pkgbuild_path,
            pkgmeta or {"globals": {}},
            extracted_profile,
        )
    else:
        pkgbuild_path = patch_pkgbuild_groups(pkgbuild_path, groups)

    success = False
    try:
        extra_env = resolve_env_vars(resolved_profile, active_consumes)
        with emit_makepkg_conf(resolved_profile, active_consumes) as conf_path:
            _invoke_with_retry(pkgbuild_path, conf_path, resolved_profile,
                               extra_env, extra_flags, interactive)
        success = True
    except RuntimeError:
        raise
    except Exception as e:
        handle_failure("tempfile_write_failed", str(e), config)
    finally:
        if extracted_profile is not None:
            if success:
                cleanup_patch_artifacts(pkgbuild_path.parent / "PKGBUILD")
            else:
                _log.warn("[PATCH]", "Build failed — leaving PKGBUILD.sysforge and pkgbuild_extracted_profile.toml in place for diagnosis")
        else:
            if success:
                if pkgbuild_path.exists():
                    pkgbuild_path.unlink()
                    _log.info("[BUILD]", f"Removed patched PKGBUILD: {pkgbuild_path}")
            else:
                _log.warn("[BUILD]", f"Build failed — leaving patched PKGBUILD in place: {pkgbuild_path}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def run(pkgbuild_path, extra_flags=None, interactive=False):
    config = load_config()
    conflict_groups = load_conflict_groups()
    inference_map = load_consumes_inference()

    try:
        pkgmeta = parse_pkgbuild(pkgbuild_path)
    except Exception as e:
        handle_failure("pkgbuild_unparseable", str(e), config)
        pkgmeta = {"globals": {}}

    pkgbuild_path = Path(pkgbuild_path).resolve()
    matched_rules = match_rules(pkgmeta, config.get("rules", []))

    build_mode = None  # resolved below after profile

    # Determine if patching is requested before full profile resolution,
    # so we can extract and inject the pkgbuild_extracted root.
    # We do a preliminary rule match here; full profile resolution follows.
    _pre_profile = resolve_profile(pkgmeta, matched_rules, config, conflict_groups)
    build_mode = _pre_profile.get("build_mode")

    extracted_profile = None
    if build_mode == "patch_pkgbuild":
        extracted_profile = extract_pkgbuild_profile(pkgmeta, pkgbuild_path)
        if extracted_profile:
            write_extracted_profile(extracted_profile, pkgbuild_path)

    resolved_profile = resolve_profile(
        pkgmeta, matched_rules, config, conflict_groups,
        extracted_profile=extracted_profile,
    )
    active_consumes = resolve_consumes(resolved_profile, pkgmeta, inference_map)
    groups = resolve_groups(pkgmeta, matched_rules, config.get("defaults", {}))

    if resolved_profile.get("clean_builddir", False):
        build_dir = pkgbuild_path.parent
        for entry in build_dir.iterdir():
            if entry.name != "PKGBUILD" and not entry.name.endswith(".PKGBUILD"):
                if entry.is_dir():
                    shutil.rmtree(entry)
                else:
                    entry.unlink()
        _log.info("[BUILD]", f"Cleaned build dir: {build_dir}")

    if build_mode == "pgo_llvm_toolchain":
        pass  # hand off to pgo handler
    else:
        run_dep_analysis(pkgmeta, config)
        _run_build(
            pkgbuild_path, resolved_profile, config, groups,
            active_consumes=active_consumes,
            extracted_profile=extracted_profile if build_mode == "patch_pkgbuild" else None,
            pkgmeta=pkgmeta,
            extra_flags=extra_flags,
            interactive=interactive,
        )


if __name__ == "__main__":
    run(sys.argv[1])
