#!/usr/bin/env bash
# iso-install.sh — install SysForge on the Arch live ISO and configure bootstrap.toml
#
# Run as root from the live Arch install environment:
#   bash tools/iso-install.sh
#
# After this script completes, run the bootstrap pipeline:
#   sysforge run pipeline --state-dir /mnt/var/lib/sysforge

set -euo pipefail

REPO="https://github.com/KeithRaghubar/sysforge.git"
CLONE_DIR="$HOME/sysforge"

# ── helpers ───────────────────────────────────────────────────────────────────

_die()    { echo "ERROR: $*" >&2; exit 1; }
_header() { echo; echo "── $*"; }

_prompt_required() {
    local label=$1 value
    while true; do
        read -r -p "  $label: " value
        [[ -n "$value" ]] && { echo "$value"; return; }
        echo "  (required — cannot be empty)" >&2
    done
}

_prompt_default() {
    local label=$1 default=$2 value
    read -r -p "  $label [$default]: " value
    echo "${value:-$default}"
}

_prompt_choice() {
    local label=$1 default=$2 a=$3 b=$4 value
    while true; do
        read -r -p "  $label [$default]: " value
        value="${value:-$default}"
        [[ "$value" == "$a" || "$value" == "$b" ]] && { echo "$value"; return; }
        echo "  Must be $a or $b" >&2
    done
}

_prompt_timezone() {
    local value
    while true; do
        read -r -p "  Timezone (e.g. America/Toronto, Europe/London, UTC): " value
        [[ -z "$value" ]] && { echo "  (required — cannot be empty)" >&2; continue; }
        [[ -e "/usr/share/zoneinfo/$value" ]] && { echo "$value"; return; }
        echo "  Invalid timezone. Check /usr/share/zoneinfo/ for valid values." >&2
    done
}

_prompt_password() {
    local p1 p2
    while true; do
        read -r -s -p "  Root password: " p1; echo >&2
        [[ -z "$p1" ]] && { echo "  (required — cannot be empty)" >&2; continue; }
        read -r -s -p "  Confirm password: " p2; echo >&2
        [[ "$p1" == "$p2" ]] && { echo "$p1"; return; }
        echo "  Passwords do not match — try again." >&2
    done
}

# ── 1. Check internet ─────────────────────────────────────────────────────────

_header "Checking internet connectivity"
if ! ping -c 1 -W 3 archlinux.org &>/dev/null; then
    echo "  No connectivity. Connect first:"
    echo "    Wired:    ip link  (usually automatic)"
    echo "    Wireless: iwctl station wlan0 connect \"SSID\""
    _die "Cannot reach archlinux.org"
fi
echo "  OK"

# ── 2. Install SysForge ───────────────────────────────────────────────────────

_header "Installing SysForge"
pacman -Sy --needed --noconfirm git python-pip

if [[ -d "$CLONE_DIR/.git" ]]; then
    echo "  Updating existing clone: $CLONE_DIR"
    git -C "$CLONE_DIR" pull --rebase --quiet
else
    git clone --quiet "$REPO" "$CLONE_DIR"
fi

pip install --break-system-packages --no-deps --quiet "$CLONE_DIR"
echo "  Installed: $(sysforge --help 2>&1 | head -1 || echo sysforge)"

# ── 3. Config files ───────────────────────────────────────────────────────────

_header "Installing config files"
if [[ ! -d /etc/sysforge ]]; then
    cp -r "$CLONE_DIR/etc/sysforge" /etc/sysforge
    echo "  Copied to /etc/sysforge"
else
    echo "  /etc/sysforge already exists — skipping"
fi

# ── 4. Configure bootstrap.toml ───────────────────────────────────────────────

_header "Configure bootstrap.toml"
echo
echo "  Available block devices:"
lsblk -d -o NAME,SIZE,MODEL --noheadings | grep -v '^loop' | sed 's/^/    /'
echo

DEVICE=$(_prompt_required "Block device to install on (e.g. /dev/sda or /dev/nvme0n1)")
ROOT_FS=$(_prompt_choice   "Root filesystem [ext4/btrfs]" "ext4" "ext4" "btrfs")
HOSTNAME=$(_prompt_required "Hostname")
LOCALE=$(_prompt_default    "Locale" "en_US.UTF-8")
TIMEZONE=$(_prompt_timezone)
KEYMAP=$(_prompt_default    "Keymap" "us")
COUNTRY=$(_prompt_default   "Mirror country for reflector (leave blank for all)" "")
ROOT_PASSWORD=$(_prompt_password)

# Build optional countries line
if [[ -n "$COUNTRY" ]]; then
    COUNTRIES_LINE="countries = [\"$COUNTRY\"]"
else
    COUNTRIES_LINE="# countries = []  # set to filter mirrors by country"
fi

cat > /etc/sysforge/bootstrap.toml << EOF
# bootstrap.toml — generated by iso-install.sh
target = "/mnt"

[partition]
device       = "$DEVICE"
esp_size_mib = 512
root_fs      = "$ROOT_FS"

[system]
hostname      = "$HOSTNAME"
locale        = "$LOCALE"
timezone      = "$TIMEZONE"
keymap        = "$KEYMAP"
root_password = "$ROOT_PASSWORD"

[mirror]
$COUNTRIES_LINE
protocol = "https"
age      = 12
EOF

_header "bootstrap.toml written"
echo
sed 's/^\(root_password\s*=\s*\).*/\1"[hidden]"/' /etc/sysforge/bootstrap.toml
echo
echo "────────────────────────────────────────────────"
echo "  To edit further:  vim /etc/sysforge/bootstrap.toml"
echo "  To run pipeline:  sysforge run pipeline --state-dir /mnt/var/lib/sysforge"
echo "────────────────────────────────────────────────"
